game:
  type: PrisonersDilemma
  kwargs:
    payoff_matrix:
      CC: [3, 3]
      CD: [0, 5]
      DC: [5, 0]
      DD: [1, 1]

evolution:
  initial_population: uniform
  steps: 100

mechanism:
  type: ReputationPrisonersDilemma

agents:
  - llm:
      provider: HFInstance
      model: Qwen2.5-7B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Qwen2.5-7B-Instruct
      kwargs:
        max_new_tokens: 1024
    type: IOAgent

  - llm:
      provider: HFInstance
      model: Mistral-7B-Instruct-v0.3
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Mistral-7B-Instruct-v0.3
      kwargs:
        max_new_tokens: 1024
    type: IOAgent

  - llm:
      provider: HFInstance
      model: Llama-3.2-3B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Llama-3.2-3B-Instruct
      kwargs:
        max_new_tokens: 1024
    type: IOAgent

  - llm:
      provider: HFInstance
      model: gemma-2-9b-it
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: gemma-2-9b-it
      kwargs:
        max_new_tokens: 1024
    type: IOAgent

  - llm:
      provider: HFInstance
      model: Qwen3-14B
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Qwen3-14B
      kwargs:
        max_new_tokens: 1024
    type: IOAgent